Message.create!([
  {client: "WM", message_id: "RCV0001", message_description: "Location \#{message_param[0]} not found", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil},
  {client: "WM", message_id: "RCV0002", message_description: "Location \#{message_param[0]}  is not valid receiving location", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil},
  {client: "WM", message_id: "RCV0003", message_description: "Dock Door occupied by another shipment", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil},
  {client: "WM", message_id: "RCV0004", message_description: "Shipment \#{message_param[0]} not found", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil},
  {client: "WM", message_id: "RCV0005", message_description: "Shipment \#{message_param[0]} not assigned to this Dock Door", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil},
  {client: "WM", message_id: "RCV0006", message_description: "Shipment \#{message_param[0]} not initiated", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil},
  {client: "WM", message_id: "RCV0007", message_description: "Enter Case", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil},
  {client: "WM", message_id: "RCV0008", message_description: "Case \#{message_param[0]} already exists", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil},
  {client: "WM", message_id: "RCV0009", message_description: "Case \#{message_param[0]} does not exist", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil},
  {client: "WM", message_id: "RCV0010", message_description: "Case \#{message_param[0]} already received", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil},
  {client: "WM", message_id: "RCV0011", message_description: "Item \#{message_param[0]} does not exist in Itemmaster", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil},
  {client: "WM", message_id: "RCV0012", message_description: "Item \#{message_param[0]} not found in this shipment", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil},
  {client: "WM", message_id: "RCV0013", message_description: "Item \#{message_param[0]} is not associated to this Case", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil},
  {client: "WM", message_id: "RCV0014", message_description: "Quantity entered does not match with the qty on the case", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil},
  {client: "WM", message_id: "RCV0015", message_description: "Quantity received exceeds shipped quantity", message_type: nil, message_severity: nil, attribute1: nil, attribute2: nil, attribute3: nil, attribute4: nil, attribute5: nil, attribute6: nil, attribute7: nil, attribute8: nil, attribute9: nil, attribute10: nil, update_date: nil, updated_user: nil, updated_prc: nil}
])
