class CreateLocationInventories < ActiveRecord::Migration
  def change
    create_table :location_inventories do |t|
      t.string :client
      t.string :warehouse
      t.string :building
      t.string :channel
      t.string :Location_type
      t.string :area
      t.string :zone
      t.string :aisle
      t.string :bay
      t.string :level
      t.string :position
      t.integer :sequence
      t.string :barcode
      t.string :item
      t.string :sku_attribute1
      t.string :sku_attribute2
      t.string :sku_attribute3
      t.string :sku_attribute4
      t.string :sku_attribute5
      t.string :sku_attribute6
      t.string :sku_attribute7
      t.string :sku_attribute8
      t.string :sku_attribute9
      t.string :sku_attribute10
      t.string :concept
      t.string :description
      t.string :short_desc
      t.string :inventory_type
      t.integer :quantity
      t.integer :total_qty
      t.integer :allocated_qty
      t.integer :pending_repl_qty
      t.integer :maximum_cases
      t.integer :pending_repl_cases
      t.integer :minimum_units
      t.integer :maximum_units
      t.integer :maximum_cases
      t.string :replenish_locn
      t.string :case_id
      t.string :lot_control_nbr
      t.string :serial_nbr
      t.string :coo
      t.string :order_nbr
      t.string :allocation_type
      t.string :allocation_nbr
      t.string :pick_type
      t.string :pick_nbr
      t.string :abc_code
      t.string :hold_type
      t.string :hold_code
      t.string :cycle_counted
      t.datetime :cycle_counted_date
      t.string :cycle_counted_by
      t.string :discrepancies
      t.string :task_type
      t.integer :task_nbr
      t.string :climate_control
      t.string :minimum_temp
      t.string :maximum_temp
      t.string :lot_control_only
      t.string :multi_lot_location
      t.string :serial_nbr_only
      t.string :multi_coo_location
      t.string :single_sku_locn
      t.string :dedicated_sku_locn
      t.string :default_putaway_type
      t.string :secured_locn_type
      t.integer :maximum_wgt
      t.integer :length
      t.integer :height
      t.integer :width
      t.integer :volume
      t.string :preferred_pallet_type
      t.integer :maximum_pallets
      t.string :preferred_case_type
      t.integer :maximum_cases
      t.integer :minimum_units
      t.integer :maximum_units
      t.string :combine_locn
      t.string :combine_seq
      t.string :equipment_type
      t.string :record_status
      t.datetime :created_date
      t.string :created_user
      t.string :created_prc
      t.datetime :update_date
      t.string :updated_user
      t.string :updated_prc
      t.string :comments
      t.string :on_hold
      t.string :hold_code
      t.string :record_status
      t.datetime :created_date
      t.string :created_user
      t.string :created_prc
      t.datetime :update_date
      t.string :updated_user
      t.string :updated_prc

      t.timestamps
    end
  end
  def down
    drop_table :location_inventories
  end
end
