class CreateCaseHeaders < ActiveRecord::Migration
  def change
    create_table :case_headers do |t|
      t.string :client
      t.string :warehouse
      t.string :channel
      t.string :building
      t.string :case_id
      t.string :pallet_id
      t.string :status
      t.string :item
      t.string :sku_attribute1
      t.string :sku_attribute2
      t.string :sku_attribute3
      t.string :sku_attribute4
      t.string :sku_attribute5
      t.string :sku_attribute6
      t.string :sku_attribute7
      t.string :sku_attribute8
      t.string :sku_attribute9
      t.string :sku_attribute10
      t.string :concept
      t.string :description
      t.string :short_desc
      t.string :barcode
      t.string :inventory_type
      t.string :Location_type
      t.string :area
      t.string :zone
      t.string :aisle
      t.string :bay
      t.string :level
      t.string :position
      t.string :previous_locn_type
      t.string :previous_area
      t.string :previous_zone
      t.string :previous_aisle
      t.string :previous_bay
      t.string :previous_level
      t.string :previous_position
      t.integer :quantity
      t.integer :allocated_qty
      t.string :purchase_order_nbr
      t.integer :poline_nbr
      t.string :shipment_nbr
      t.integer :sequence
      t.string :appointment_nbr
      t.string :vendor_nbr
      t.string :vendor_factory
      t.string :coo
      t.string :track_lotcontrol
      t.string :track_serial_nbr
      t.string :track_coo
      t.string :climate_control
      t.string :order_type
      t.string :order_nbr
      t.string :allocation_type
      t.string :allocation_nbr
      t.string :pick_type
      t.string :pick_nbr
      t.integer :total_weight
      t.integer :total_volume
      t.string :case_type
      t.integer :case_len
      t.integer :cases_wdt
      t.integer :case_hgt
      t.string :multi_sku
      t.string :conveyable
      t.integer :inner_pack_qty
      t.integer :case_pack_qty
      t.string :perishble
      t.string :special_handling
      t.string :qa_auditted
      t.string :audit_nbr
      t.string :priority_type
      t.string :priority_nbr
      t.string :task_type
      t.string :task_nbr
      t.string :wave_type
      t.string :wave_nbr
      t.string :split_case
      t.string :parent_case_id
      t.string :lable_type
      t.string :transfer
      t.string :transfer_from
      t.string :form_co
      t.string :from_div
      t.string :transfer_to
      t.string :to_co
      t.string :to_div
      t.string :cross_dock
      t.datetime :received_date
      t.string :received_by
      t.string :case_verified
      t.datetime :verified_date
      t.string :verified_by
      t.string :comments
      t.string :on_hold
      t.string :hold_code
      t.string :record_status
      t.string :attribute1
      t.string :attribute2
      t.string :attribute3
      t.string :attribute4
      t.string :attribute5
      t.string :attribute6
      t.string :attribute7
      t.string :attribute8
      t.string :attribute9
      t.string :attribute10
      t.string :attribute11
      t.string :attribute12
      t.string :attribute13
      t.string :attribute14
      t.string :attribute15
      t.string :attribute16
      t.string :attribute17
      t.string :attribute18
      t.string :attribute19
      t.string :attribute20
      t.string :attribute21
      t.string :attribute22
      t.string :attribute23
      t.string :attribute24
      t.string :attribute25
      t.datetime :created_date
      t.string :created_user
      t.string :created_prc
      t.datetime :update_date
      t.string :updated_user
      t.string :updated_prc

      t.timestamps
    end
  end
  def down
    drop_table :case_headers
  end
end
