class CreateItemMasters < ActiveRecord::Migration
  def change
    create_table :item_masters do |t|
      t.string :client
      t.string :warehouse
      t.string :channel
      t.string :building
      t.string :item
      t.string :sku_attribute1
      t.string :sku_attribute2
      t.string :sku_attribute3
      t.string :sku_attribute4
      t.string :sku_attribute5
      t.string :sku_attribute6
      t.string :sku_attribute7
      t.string :sku_attribute8
      t.string :sku_attribute9
      t.string :sku_attribute10
      t.string :sku_attribute11
      t.string :sku_attribute12
      t.string :sku_attribute13
      t.string :sku_attribute14
      t.string :sku_attribute15
      t.string :sku_attribute16
      t.string :sku_attribute17
      t.string :sku_attribute18
      t.string :sku_attribute19
      t.string :sku_attribute20
      t.string :sku_attribute21
      t.string :sku_attribute22
      t.string :sku_attribute23
      t.string :sku_attribute24
      t.string :sku_attribute25
      t.string :sku_attribute26
      t.string :sku_attribute27
      t.string :sku_attribute28
      t.string :sku_attribute29
      t.string :sku_attribute30
      t.string :concept
      t.string :description
      t.string :short_desc
      t.string :barcode
      t.string :unit_putaway_type
      t.string :sku_location_type
      t.string :case_putaway_type
      t.string :pallet_putaway_type
      t.string :suggested_zone
      t.string :suggested_act_zone
      t.string :active_locn_cnt_factor
      t.string :reserve_locn_cnt_factor
      t.string :wave_proc_type
      t.string :uom
      t.string :selling_uom
      t.string :stocking_uom
      t.string :track_lotcontrol
      t.string :track_serial_nbr
      t.string :track_coo
      t.string :pallet_type
      t.string :carton_type
      t.string :carton_brk_attr
      t.string :coo
      t.string :multiple_coo
      t.string :volatility_code
      t.integer :inner_pack_qty
      t.integer :box_qty
      t.integer :standard_case_qty
      t.decimal :case_len
      t.decimal :case_wdt
      t.decimal :case_depth
      t.integer :max_cases_stacked
      t.integer :no_ofcases_per_pallet
      t.integer :pallet_qty
      t.string :coveyable
      t.integer :quantity_audit_per
      t.integer :minimum_act_inv
      t.integer :maximum_act_inv
      t.string :date_sensitivity
      t.string :product_temp_zone
      t.string :trailer_temp_zone
      t.string :haz_code
      t.string :hts_code
      t.string :nmfc_code
      t.string :topself_eligible
      t.string :crushablity_code
      t.string :inner_ctn_type
      t.string :stackbility_of_items
      t.string :goh
      t.string :track_cases_in_act
      t.integer :product_life_inshelf
      t.string :ship_alone
      t.string :case_consume_pty
      t.decimal :unit_len
      t.decimal :unit_hgt
      t.decimal :unit_wdt
      t.decimal :unit_wgt
      t.decimal :unit_vol
      t.decimal :cavity_len
      t.decimal :cavity_wdt
      t.decimal :cavity_hgtt
      t.decimal :maximum_nest
      t.string :vendor_nbr
      t.string :inventory_type
      t.string :status
      t.string :department
      t.decimal :average_wgt_cost
      t.decimal :unit_cost
      t.decimal :retail_price
      t.string :special_inst1
      t.string :special_inst2
      t.string :special_inst3
      t.string :special_inst4
      t.string :special_inst5
      t.string :special_inst6
      t.string :special_inst7
      t.string :special_inst8
      t.string :special_inst9
      t.string :special_inst10
      t.datetime :created_date
      t.string :created_user
      t.string :created_prc
      t.datetime :update_date
      t.string :updated_user
      t.string :updated_prc

      t.timestamps
    end
  end
  
  def down
    drop_table :item_masters
  end
end
